name: nsideas
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.02+3
environment:
  sdk: '>=3.2.0-238.0.dev <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  google_mobile_ads:

  cloud_firestore: ^4.13.6
  fluttertoast: ^8.2.4
  email_validator: ^2.1.17
  mailer: ^6.0.1
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  photo_view: ^0.14.0
  path_provider: ^2.1.1
  http: ^1.1.2
  url_launcher: ^6.2.2
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - lib/images/