name: nsideas
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+10
environment:
  sdk: '>=3.2.0-238.0.dev <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  firebase_auth:
  firebase_core:
  firebase_messaging:
  cloud_firestore:
  fluttertoast:
  email_validator:
  mailer:
  carousel_slider:
  shared_preferences:
  intl:
  google_sign_in:
  path_provider:
  http:
  url_launcher:
  youtube_player_flutter:
  flutter_rating_bar:
  pdfx:
  firebase_analytics:

#  open_filex:
  firebase_storage:
#  encrypt:
  flutter_svg:
  flutter_local_notifications:
  rxdart:
  file_picker:
  flutter_highlight:
  google_mobile_ads:
  google_fonts:
  badges:
  firebase_database:


#  video_player:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/