// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBscgTWKBCQF8Udh5wFyDDqHcB-PQ2873M',
    appId: '1:503839723767:web:708821849baccb2e8a43f2',
    messagingSenderId: '503839723767',
    projectId: 'ns-ideas-app',
    authDomain: 'ns-ideas-app.firebaseapp.com',
    databaseURL: 'https://ns-ideas-app-default-rtdb.firebaseio.com',
    storageBucket: 'ns-ideas-app.appspot.com',
    measurementId: 'G-7XVPR9RFXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEZH-6FhsKTWjPb59jkCAPfrbKBerUfTk',
    appId: '1:503839723767:android:f869ec1115bcf60f8a43f2',
    messagingSenderId: '503839723767',
    projectId: 'ns-ideas-app',
    databaseURL: 'https://ns-ideas-app-default-rtdb.firebaseio.com',
    storageBucket: 'ns-ideas-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2XYfehfYdfd8hio7Qpq3XGPkYQls_n5g',
    appId: '1:503839723767:ios:37353c44573f837d8a43f2',
    messagingSenderId: '503839723767',
    projectId: 'ns-ideas-app',
    databaseURL: 'https://ns-ideas-app-default-rtdb.firebaseio.com',
    storageBucket: 'ns-ideas-app.appspot.com',
    androidClientId: '503839723767-bvkrrfg885ijuj26l79at4hkc9rqp96g.apps.googleusercontent.com',
    iosClientId: '503839723767-h1e4k2r40kfn5u4cvkeqauh84qu6sjb5.apps.googleusercontent.com',
    iosBundleId: 'com.nimmalasujith.nsideasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2XYfehfYdfd8hio7Qpq3XGPkYQls_n5g',
    appId: '1:503839723767:ios:9b0b652edc81895e8a43f2',
    messagingSenderId: '503839723767',
    projectId: 'ns-ideas-app',
    databaseURL: 'https://ns-ideas-app-default-rtdb.firebaseio.com',
    storageBucket: 'ns-ideas-app.appspot.com',
    androidClientId: '503839723767-bvkrrfg885ijuj26l79at4hkc9rqp96g.apps.googleusercontent.com',
    iosClientId: '503839723767-8oc7kt8unv98t5g3drsi881mvue6gp68.apps.googleusercontent.com',
    iosBundleId: 'com.nimmalasujith.nsideas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBscgTWKBCQF8Udh5wFyDDqHcB-PQ2873M',
    appId: '1:503839723767:web:4b639f855f098b8b8a43f2',
    messagingSenderId: '503839723767',
    projectId: 'ns-ideas-app',
    authDomain: 'ns-ideas-app.firebaseapp.com',
    databaseURL: 'https://ns-ideas-app-default-rtdb.firebaseio.com',
    storageBucket: 'ns-ideas-app.appspot.com',
    measurementId: 'G-0KNLP1JYYX',
  );

}